name: Pre-Build Container
on: [push]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Prebuild Image
      run: |
        cd $GITHUB_WORKSPACE
        echo ${PASSWORD} | docker login -u $USERNAME --password-stdin
        docker build -t hamelsmu/gke-kubeconfig -f prebuild.Dockerfile .
        docker push hamelsmu/gke-kubeconfig
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
